// <auto-generated />
namespace _04_InsecureDirectObjectReference.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AccountId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccountId));
        
        string IMigrationMetadata.Id
        {
            get { return "201601261757278_AccountId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
